using Dapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Portfolio.Api.Services;
using Portfolio.Data;
using Portfolio.Data.DTOs;
using Portfolio.Data.Models;

namespace Portfolio.Api.Controllers;

[ApiController, Route("api/admin"), Authorize(Roles = "Admin,Editor")]
public class AdminController : ControllerBase
{
    private readonly SqlConnectionFactory _db;
    private readonly ErrorLogService _err;
    public AdminController(SqlConnectionFactory db, ErrorLogService err) { _db = db; _err = err; }

    [HttpGet("dashboard")] public async Task<IActionResult> Dashboard() { try { using var c=_db.Create(); return Ok(ApiResponse<DashboardStats>.Ok(new DashboardStats { TotalProjects=await c.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM Projects"), TotalSkills=await c.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM Skills"), TotalMessages=await c.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM ContactMessages"), UnreadMessages=await c.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM ContactMessages WHERE IsRead=0"), TotalTestimonials=await c.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM Testimonials") })); } catch(Exception ex){await _err.LogAsync(ex,"Admin.Dashboard");return StatusCode(500,ApiResponse<object>.Fail("Error loading dashboard."));} }

    [HttpGet("profile")] public async Task<IActionResult> GetProfile() { try{using var c=_db.Create();var p=await c.QueryFirstOrDefaultAsync<Profile>("SELECT * FROM Profile");return p==null?NotFound():Ok(ApiResponse<Profile>.Ok(p));}catch(Exception ex){await _err.LogAsync(ex,"Admin.GetProfile");return StatusCode(500,ApiResponse<object>.Fail("Error."));} }
    [HttpPut("profile")] public async Task<IActionResult> UpdateProfile([FromBody] Profile m) { try{using var c=_db.Create();var e=await c.QueryFirstOrDefaultAsync<Profile>("SELECT * FROM Profile");if(e==null)await c.ExecuteAsync("INSERT INTO Profile (FullName,Title,TaglineLine1,TaglineLine2,TaglineLine3,Bio,ProfileImageUrl,ResumeFileUrl,Email,LinkedIn,GitHub,Twitter,Location,ShowreelUrl,MetaDescription,MetaKeywords,OgImageUrl,GoogleAnalyticsId,SiteUrl,UpdatedAt) VALUES (@FullName,@Title,@TaglineLine1,@TaglineLine2,@TaglineLine3,@Bio,@ProfileImageUrl,@ResumeFileUrl,@Email,@LinkedIn,@GitHub,@Twitter,@Location,@ShowreelUrl,@MetaDescription,@MetaKeywords,@OgImageUrl,@GoogleAnalyticsId,@SiteUrl,SYSUTCDATETIME())",m);else await c.ExecuteAsync("UPDATE Profile SET FullName=@FullName,Title=@Title,TaglineLine1=@TaglineLine1,TaglineLine2=@TaglineLine2,TaglineLine3=@TaglineLine3,Bio=@Bio,ProfileImageUrl=@ProfileImageUrl,ResumeFileUrl=@ResumeFileUrl,Email=@Email,LinkedIn=@LinkedIn,GitHub=@GitHub,Twitter=@Twitter,Location=@Location,ShowreelUrl=@ShowreelUrl,MetaDescription=@MetaDescription,MetaKeywords=@MetaKeywords,OgImageUrl=@OgImageUrl,GoogleAnalyticsId=@GoogleAnalyticsId,SiteUrl=@SiteUrl,UpdatedAt=SYSUTCDATETIME()",m);return Ok(ApiResponse<object>.Ok(new{},"Profile updated"));}catch(Exception ex){await _err.LogAsync(ex,"Admin.UpdateProfile");return StatusCode(500,ApiResponse<object>.Fail("Error."));} }

    [HttpGet("projects")] public async Task<IActionResult> GetProjects() { try{using var c=_db.Create();return Ok(ApiResponse<List<Project>>.Ok((await c.QueryAsync<Project>("SELECT * FROM Projects ORDER BY SortOrder")).ToList()));}catch(Exception ex){await _err.LogAsync(ex,"Admin.GetProjects");return StatusCode(500,ApiResponse<object>.Fail("Error."));} }
    [HttpGet("projects/{id:int}")] public async Task<IActionResult> GetProject(int id) { try{using var c=_db.Create();var p=await c.QueryFirstOrDefaultAsync<Project>("SELECT * FROM Projects WHERE Id=@Id",new{Id=id});return p==null?NotFound():Ok(ApiResponse<Project>.Ok(p));}catch(Exception ex){await _err.LogAsync(ex,$"Admin.GetProject({id})");return StatusCode(500,ApiResponse<object>.Fail("Error."));} }
    [HttpPost("projects")] public async Task<IActionResult> CreateProject([FromBody] Project m) { try{using var c=_db.Create();var id=await c.QuerySingleAsync<int>("INSERT INTO Projects (Title,Slug,Description,ShortDesc,Category,Technologies,MockupClass,CardRotation,SortOrder,IsFeatured,IsPublished,ContractId,ClientName,CreatedAt,UpdatedAt) OUTPUT INSERTED.Id VALUES (@Title,@Slug,@Description,@ShortDesc,@Category,@Technologies,@MockupClass,@CardRotation,@SortOrder,@IsFeatured,@IsPublished,@ContractId,@ClientName,SYSUTCDATETIME(),SYSUTCDATETIME())",m);m.Id=id;return Ok(ApiResponse<Project>.Ok(m,"Created"));}catch(Exception ex){await _err.LogAsync(ex,"Admin.CreateProject");return StatusCode(500,ApiResponse<object>.Fail("Error."));} }
    [HttpPut("projects/{id}")] public async Task<IActionResult> UpdateProject(int id, [FromBody] Project m) { try{using var c=_db.Create();await c.ExecuteAsync("UPDATE Projects SET Title=@Title,Slug=@Slug,Description=@Description,ShortDesc=@ShortDesc,Category=@Category,Technologies=@Technologies,MockupClass=@MockupClass,CardRotation=@CardRotation,SortOrder=@SortOrder,IsFeatured=@IsFeatured,IsPublished=@IsPublished,ContractId=@ContractId,ClientName=@ClientName,UpdatedAt=SYSUTCDATETIME() WHERE Id=@Id",new{m.Title,m.Slug,m.Description,m.ShortDesc,m.Category,m.Technologies,m.MockupClass,m.CardRotation,m.SortOrder,m.IsFeatured,m.IsPublished,m.ContractId,m.ClientName,Id=id});return Ok(ApiResponse<object>.Ok(new{},"Updated"));}catch(Exception ex){await _err.LogAsync(ex,$"Admin.UpdateProject({id})");return StatusCode(500,ApiResponse<object>.Fail("Error."));} }
    [HttpDelete("projects/{id}")] public async Task<IActionResult> DeleteProject(int id) { try{using var c=_db.Create();await c.ExecuteAsync("DELETE FROM Projects WHERE Id=@Id",new{Id=id});return Ok(ApiResponse<object>.Ok(new{},"Deleted"));}catch(Exception ex){await _err.LogAsync(ex,$"Admin.DeleteProject({id})");return StatusCode(500,ApiResponse<object>.Fail("Error."));} }

    [HttpGet("skills")] public async Task<IActionResult> GetSkills() { try{using var c=_db.Create();return Ok(ApiResponse<List<Skill>>.Ok((await c.QueryAsync<Skill>("SELECT * FROM Skills ORDER BY SortOrder")).ToList()));}catch(Exception ex){await _err.LogAsync(ex,"Admin.GetSkills");return StatusCode(500,ApiResponse<object>.Fail("Error."));} }
    [HttpPost("skills")] public async Task<IActionResult> CreateSkill([FromBody] Skill m) { try{using var c=_db.Create();var id=await c.QuerySingleAsync<int>("INSERT INTO Skills (Name,Category,Proficiency,IsTag,SortOrder,CreatedAt,UpdatedAt) OUTPUT INSERTED.Id VALUES (@Name,@Category,@Proficiency,@IsTag,@SortOrder,SYSUTCDATETIME(),SYSUTCDATETIME())",m);m.Id=id;return Ok(ApiResponse<Skill>.Ok(m,"Created"));}catch(Exception ex){await _err.LogAsync(ex,"Admin.CreateSkill");return StatusCode(500,ApiResponse<object>.Fail("Error."));} }
    [HttpPut("skills/{id}")] public async Task<IActionResult> UpdateSkill(int id, [FromBody] Skill m) { try{using var c=_db.Create();await c.ExecuteAsync("UPDATE Skills SET Name=@Name,Category=@Category,Proficiency=@Proficiency,IsTag=@IsTag,SortOrder=@SortOrder,UpdatedAt=SYSUTCDATETIME() WHERE Id=@Id",new{m.Name,m.Category,m.Proficiency,m.IsTag,m.SortOrder,Id=id});return Ok(ApiResponse<object>.Ok(new{},"Updated"));}catch(Exception ex){await _err.LogAsync(ex,$"Admin.UpdateSkill({id})");return StatusCode(500,ApiResponse<object>.Fail("Error."));} }
    [HttpDelete("skills/{id}")] public async Task<IActionResult> DeleteSkill(int id) { try{using var c=_db.Create();await c.ExecuteAsync("DELETE FROM Skills WHERE Id=@Id",new{Id=id});return Ok(ApiResponse<object>.Ok(new{},"Deleted"));}catch(Exception ex){await _err.LogAsync(ex,$"Admin.DeleteSkill({id})");return StatusCode(500,ApiResponse<object>.Fail("Error."));} }

    [HttpGet("experiences")] public async Task<IActionResult> GetExperiences() { try{using var c=_db.Create();return Ok(ApiResponse<List<Experience>>.Ok((await c.QueryAsync<Experience>("SELECT * FROM Experiences ORDER BY SortOrder")).ToList()));}catch(Exception ex){await _err.LogAsync(ex,"Admin.GetExperiences");return StatusCode(500,ApiResponse<object>.Fail("Error."));} }
    [HttpPost("experiences")] public async Task<IActionResult> CreateExperience([FromBody] Experience m) { try{using var c=_db.Create();var id=await c.QuerySingleAsync<int>("INSERT INTO Experiences (Company,Role,Description,StartDate,EndDate,Location,SortOrder,CreatedAt,UpdatedAt) OUTPUT INSERTED.Id VALUES (@Company,@Role,@Description,@StartDate,@EndDate,@Location,@SortOrder,SYSUTCDATETIME(),SYSUTCDATETIME())",m);m.Id=id;return Ok(ApiResponse<Experience>.Ok(m,"Created"));}catch(Exception ex){await _err.LogAsync(ex,"Admin.CreateExperience");return StatusCode(500,ApiResponse<object>.Fail("Error."));} }
    [HttpPut("experiences/{id}")] public async Task<IActionResult> UpdateExperience(int id, [FromBody] Experience m) { try{using var c=_db.Create();await c.ExecuteAsync("UPDATE Experiences SET Company=@Company,Role=@Role,Description=@Description,StartDate=@StartDate,EndDate=@EndDate,Location=@Location,SortOrder=@SortOrder,UpdatedAt=SYSUTCDATETIME() WHERE Id=@Id",new{m.Company,m.Role,m.Description,m.StartDate,m.EndDate,m.Location,m.SortOrder,Id=id});return Ok(ApiResponse<object>.Ok(new{},"Updated"));}catch(Exception ex){await _err.LogAsync(ex,$"Admin.UpdateExperience({id})");return StatusCode(500,ApiResponse<object>.Fail("Error."));} }
    [HttpDelete("experiences/{id}")] public async Task<IActionResult> DeleteExperience(int id) { try{using var c=_db.Create();await c.ExecuteAsync("DELETE FROM Experiences WHERE Id=@Id",new{Id=id});return Ok(ApiResponse<object>.Ok(new{},"Deleted"));}catch(Exception ex){await _err.LogAsync(ex,$"Admin.DeleteExperience({id})");return StatusCode(500,ApiResponse<object>.Fail("Error."));} }

    [HttpGet("testimonials")] public async Task<IActionResult> GetTestimonials() { try{using var c=_db.Create();return Ok(ApiResponse<List<Testimonial>>.Ok((await c.QueryAsync<Testimonial>("SELECT * FROM Testimonials ORDER BY SortOrder")).ToList()));}catch(Exception ex){await _err.LogAsync(ex,"Admin.GetTestimonials");return StatusCode(500,ApiResponse<object>.Fail("Error."));} }
    [HttpPost("testimonials")] public async Task<IActionResult> CreateTestimonial([FromBody] Testimonial m) { try{using var c=_db.Create();var id=await c.QuerySingleAsync<int>("INSERT INTO Testimonials (ClientName,ClientTitle,Content,Rating,IsPublished,SortOrder,CreatedAt,UpdatedAt) OUTPUT INSERTED.Id VALUES (@ClientName,@ClientTitle,@Content,@Rating,@IsPublished,@SortOrder,SYSUTCDATETIME(),SYSUTCDATETIME())",m);m.Id=id;return Ok(ApiResponse<Testimonial>.Ok(m,"Created"));}catch(Exception ex){await _err.LogAsync(ex,"Admin.CreateTestimonial");return StatusCode(500,ApiResponse<object>.Fail("Error."));} }
    [HttpPut("testimonials/{id}")] public async Task<IActionResult> UpdateTestimonial(int id, [FromBody] Testimonial m) { try{using var c=_db.Create();await c.ExecuteAsync("UPDATE Testimonials SET ClientName=@ClientName,ClientTitle=@ClientTitle,Content=@Content,Rating=@Rating,IsPublished=@IsPublished,SortOrder=@SortOrder,UpdatedAt=SYSUTCDATETIME() WHERE Id=@Id",new{m.ClientName,m.ClientTitle,m.Content,m.Rating,m.IsPublished,m.SortOrder,Id=id});return Ok(ApiResponse<object>.Ok(new{},"Updated"));}catch(Exception ex){await _err.LogAsync(ex,$"Admin.UpdateTestimonial({id})");return StatusCode(500,ApiResponse<object>.Fail("Error."));} }
    [HttpDelete("testimonials/{id}")] public async Task<IActionResult> DeleteTestimonial(int id) { try{using var c=_db.Create();await c.ExecuteAsync("DELETE FROM Testimonials WHERE Id=@Id",new{Id=id});return Ok(ApiResponse<object>.Ok(new{},"Deleted"));}catch(Exception ex){await _err.LogAsync(ex,$"Admin.DeleteTestimonial({id})");return StatusCode(500,ApiResponse<object>.Fail("Error."));} }

    [HttpGet("messages")] public async Task<IActionResult> GetMessages(bool? unreadOnly=null) { try{using var c=_db.Create();var sql="SELECT * FROM ContactMessages"+(unreadOnly==true?" WHERE IsRead=0":"")+" ORDER BY CreatedAt DESC";return Ok(ApiResponse<List<ContactMessage>>.Ok((await c.QueryAsync<ContactMessage>(sql)).ToList()));}catch(Exception ex){await _err.LogAsync(ex,"Admin.GetMessages");return StatusCode(500,ApiResponse<object>.Fail("Error."));} }
    [HttpPut("messages/{id}/read")] public async Task<IActionResult> MarkRead(int id) { try{using var c=_db.Create();await c.ExecuteAsync("UPDATE ContactMessages SET IsRead=1,RepliedAt=SYSUTCDATETIME() WHERE Id=@Id",new{Id=id});return Ok(ApiResponse<object>.Ok(new{},"Marked read"));}catch(Exception ex){await _err.LogAsync(ex,$"Admin.MarkRead({id})");return StatusCode(500,ApiResponse<object>.Fail("Error."));} }
    [HttpDelete("messages/{id}")] public async Task<IActionResult> DeleteMessage(int id) { try{using var c=_db.Create();await c.ExecuteAsync("DELETE FROM ContactMessages WHERE Id=@Id",new{Id=id});return Ok(ApiResponse<object>.Ok(new{},"Deleted"));}catch(Exception ex){await _err.LogAsync(ex,$"Admin.DeleteMessage({id})");return StatusCode(500,ApiResponse<object>.Fail("Error."));} }

    [HttpGet("settings")] public async Task<IActionResult> GetSettings() { try{using var c=_db.Create();return Ok(ApiResponse<List<SiteSetting>>.Ok((await c.QueryAsync<SiteSetting>("SELECT * FROM SiteSettings")).ToList()));}catch(Exception ex){await _err.LogAsync(ex,"Admin.GetSettings");return StatusCode(500,ApiResponse<object>.Fail("Error."));} }
    [HttpPut("settings/{key}")] public async Task<IActionResult> UpdateSetting(string key, [FromBody] string value) { try{using var c=_db.Create();var s=await c.QueryFirstOrDefaultAsync<SiteSetting>("SELECT * FROM SiteSettings WHERE [Key]=@K",new{K=key});if(s==null)await c.ExecuteAsync("INSERT INTO SiteSettings ([Key],Value,UpdatedAt) VALUES (@K,@V,SYSUTCDATETIME())",new{K=key,V=value});else await c.ExecuteAsync("UPDATE SiteSettings SET Value=@V,UpdatedAt=SYSUTCDATETIME() WHERE [Key]=@K",new{K=key,V=value});return Ok(ApiResponse<object>.Ok(new{},"Setting updated"));}catch(Exception ex){await _err.LogAsync(ex,$"Admin.UpdateSetting({key})");return StatusCode(500,ApiResponse<object>.Fail("Error."));} }

    [HttpGet("errors/count")] public async Task<IActionResult> ErrorCount() { try{using var c=_db.Create();return Ok(new{unresolved=await c.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM ErrorLogs WHERE IsResolved=0"),total=await c.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM ErrorLogs")});}catch{return Ok(new{unresolved=0,total=0});} }

    // ===== CONTRACTS =====
    [HttpGet("contracts")] public async Task<IActionResult> GetContracts() { try { using var c = _db.Create(); return Ok(ApiResponse<List<Contract>>.Ok((await c.QueryAsync<Contract>("SELECT * FROM Contracts ORDER BY CreatedAt DESC")).ToList())); } catch (Exception ex) { await _err.LogAsync(ex, "Admin.GetContracts"); return StatusCode(500, ApiResponse<object>.Fail("Error.")); } }
    [HttpPost("contracts")] public async Task<IActionResult> CreateContract([FromBody] Contract m) { try { using var c = _db.Create(); var id = await c.QuerySingleAsync<int>("INSERT INTO Contracts (Title,ClientName,ClientEmail,Amount,Currency,StartDate,EndDate,Status,Description,Notes,CreatedAt,UpdatedAt) OUTPUT INSERTED.Id VALUES (@Title,@ClientName,@ClientEmail,@Amount,@Currency,@StartDate,@EndDate,@Status,@Description,@Notes,SYSUTCDATETIME(),SYSUTCDATETIME())", m); m.Id = id; return Ok(ApiResponse<Contract>.Ok(m, "Created")); } catch (Exception ex) { await _err.LogAsync(ex, "Admin.CreateContract"); return StatusCode(500, ApiResponse<object>.Fail("Error.")); } }
    [HttpPut("contracts/{id}")] public async Task<IActionResult> UpdateContract(int id, [FromBody] Contract m) { try { using var c = _db.Create(); await c.ExecuteAsync("UPDATE Contracts SET Title=@Title,ClientName=@ClientName,ClientEmail=@ClientEmail,Amount=@Amount,Currency=@Currency,StartDate=@StartDate,EndDate=@EndDate,Status=@Status,Description=@Description,Notes=@Notes,UpdatedAt=SYSUTCDATETIME() WHERE Id=@Id", new { m.Title, m.ClientName, m.ClientEmail, m.Amount, m.Currency, m.StartDate, m.EndDate, m.Status, m.Description, m.Notes, Id = id }); return Ok(ApiResponse<object>.Ok(new { }, "Updated")); } catch (Exception ex) { await _err.LogAsync(ex, "Admin.UpdateContract(" + id + ")"); return StatusCode(500, ApiResponse<object>.Fail("Error.")); } }
    [HttpDelete("contracts/{id}")] public async Task<IActionResult> DeleteContract(int id) { try { using var c = _db.Create(); await c.ExecuteAsync("DELETE FROM Contracts WHERE Id=@Id", new { Id = id }); return Ok(ApiResponse<object>.Ok(new { }, "Deleted")); } catch (Exception ex) { await _err.LogAsync(ex, "Admin.DeleteContract(" + id + ")"); return StatusCode(500, ApiResponse<object>.Fail("Error.")); } }

    // ===== PROJECT PHASES =====
    [HttpGet("phases/{projectId}")] public async Task<IActionResult> GetPhases(int projectId) { try { using var c = _db.Create(); return Ok((await c.QueryAsync<ProjectPhase>("SELECT * FROM ProjectPhases WHERE ProjectId=@Pid ORDER BY SortOrder", new { Pid = projectId })).ToList()); } catch (Exception ex) { await _err.LogAsync(ex, "Admin.GetPhases(" + projectId + ")"); return StatusCode(500, ApiResponse<object>.Fail("Error.")); } }
    [HttpPost("phases")] public async Task<IActionResult> CreatePhase([FromBody] ProjectPhase m) { try { using var c = _db.Create(); var id = await c.QuerySingleAsync<int>("INSERT INTO ProjectPhases (ProjectId,Title,Description,Status,Progress,SortOrder,StartDate,EndDate,CreatedAt,UpdatedAt) OUTPUT INSERTED.Id VALUES (@ProjectId,@Title,@Description,@Status,@Progress,@SortOrder,@StartDate,@EndDate,SYSUTCDATETIME(),SYSUTCDATETIME())", m); m.Id = id; return Ok(ApiResponse<ProjectPhase>.Ok(m, "Created")); } catch (Exception ex) { await _err.LogAsync(ex, "Admin.CreatePhase"); return StatusCode(500, ApiResponse<object>.Fail("Error.")); } }
    [HttpPut("phases/{id}")] public async Task<IActionResult> UpdatePhase(int id, [FromBody] ProjectPhase m) { try { using var c = _db.Create(); await c.ExecuteAsync("UPDATE ProjectPhases SET Title=@Title,Description=@Description,Status=@Status,Progress=@Progress,SortOrder=@SortOrder,StartDate=@StartDate,EndDate=@EndDate,UpdatedAt=SYSUTCDATETIME() WHERE Id=@Id", new { m.Title, m.Description, m.Status, m.Progress, m.SortOrder, m.StartDate, m.EndDate, Id = id }); return Ok(ApiResponse<object>.Ok(new { }, "Updated")); } catch (Exception ex) { await _err.LogAsync(ex, "Admin.UpdatePhase(" + id + ")"); return StatusCode(500, ApiResponse<object>.Fail("Error.")); } }
    [HttpDelete("phases/{id}")] public async Task<IActionResult> DeletePhase(int id) { try { using var c = _db.Create(); await c.ExecuteAsync("DELETE FROM ProjectPhases WHERE Id=@Id", new { Id = id }); return Ok(ApiResponse<object>.Ok(new { }, "Deleted")); } catch (Exception ex) { await _err.LogAsync(ex, "Admin.DeletePhase(" + id + ")"); return StatusCode(500, ApiResponse<object>.Fail("Error.")); } }

    // ===== PROJECT DETAIL (with phases summary) =====
    [HttpGet("projects/{id}/detail")] public async Task<IActionResult> GetProjectDetail(int id) { try { using var c = _db.Create(); var project = await c.QueryFirstOrDefaultAsync<Project>("SELECT * FROM Projects WHERE Id=@Id", new { Id = id }); if (project == null) return NotFound(); var phases = (await c.QueryAsync<ProjectPhase>("SELECT * FROM ProjectPhases WHERE ProjectId=@Pid ORDER BY SortOrder", new { Pid = id })).ToList(); var contract = project.ContractId != null ? await c.QueryFirstOrDefaultAsync<Contract>("SELECT * FROM Contracts WHERE Id=@Id", new { Id = project.ContractId }) : null; return Ok(new { project, phases, contract, totalPhases = phases.Count, completedPhases = phases.Count(p => p.Status == "Completed") }); } catch (Exception ex) { await _err.LogAsync(ex, "Admin.GetProjectDetail(" + id + ")"); return StatusCode(500, ApiResponse<object>.Fail("Error.")); } }
}
