namespace Portfolio.Data.Models;

public class Role { public int Id { get; set; } public string Name { get; set; } = ""; public string? Description { get; set; } public DateTime CreatedAt { get; set; } }
public class User { public int Id { get; set; } public string Username { get; set; } = ""; public string Email { get; set; } = ""; public string PasswordHash { get; set; } = ""; public string? FullName { get; set; } public string? AvatarUrl { get; set; } public string? Bio { get; set; } public int RoleId { get; set; } public bool IsActive { get; set; } public DateTime? LastLoginAt { get; set; } public string? RefreshToken { get; set; } public DateTime? RefreshTokenExp { get; set; } public DateTime CreatedAt { get; set; } public DateTime UpdatedAt { get; set; } public string? RoleName { get; set; } public Role? Role { get; set; } }
public class Resource { public int Id { get; set; } public string FileName { get; set; } = ""; public string? FileContent { get; set; } public DateTime ExecutedAt { get; set; } public bool IsSuccess { get; set; } public string? ErrorMessage { get; set; } public DateTime CreatedAt { get; set; } public DateTime UpdatedAt { get; set; } }
public class Profile { public int Id { get; set; } public string FullName { get; set; } = ""; public string Title { get; set; } = ""; public string? TaglineLine1 { get; set; } public string? TaglineLine2 { get; set; } public string? TaglineLine3 { get; set; } public string? Bio { get; set; } public string? ProfileImageUrl { get; set; } public string? ResumeFileUrl { get; set; } public string? Email { get; set; } public string? LinkedIn { get; set; } public string? GitHub { get; set; } public string? Twitter { get; set; } public string? Location { get; set; } public string? ShowreelUrl { get; set; } public string? MetaDescription { get; set; } public string? MetaKeywords { get; set; } public string? OgImageUrl { get; set; } public string? GoogleAnalyticsId { get; set; } public string? SiteUrl { get; set; } public DateTime CreatedAt { get; set; } public DateTime UpdatedAt { get; set; } }
public class Project { public int Id { get; set; } public string Title { get; set; } = ""; public string Slug { get; set; } = ""; public string? Description { get; set; } public string? ShortDesc { get; set; } public string? Category { get; set; } public string? ThumbnailUrl { get; set; } public string? ImageUrls { get; set; } public string? LiveUrl { get; set; } public string? GitHubUrl { get; set; } public string? Technologies { get; set; } public string? MockupClass { get; set; } public string? CardRotation { get; set; } public int SortOrder { get; set; } public bool IsFeatured { get; set; } public bool IsPublished { get; set; } public int? ContractId { get; set; } public string? ClientName { get; set; } public DateTime? CompletedAt { get; set; } public DateTime CreatedAt { get; set; } public DateTime UpdatedAt { get; set; } }
public class ProjectImage { public int Id { get; set; } public int ProjectId { get; set; } public string ImageUrl { get; set; } = ""; public string? AltText { get; set; } public int SortOrder { get; set; } public DateTime CreatedAt { get; set; } }
public class Skill { public int Id { get; set; } public string Name { get; set; } = ""; public string Category { get; set; } = ""; public int Proficiency { get; set; } public string? IconClass { get; set; } public bool IsTag { get; set; } public int SortOrder { get; set; } public DateTime CreatedAt { get; set; } public DateTime UpdatedAt { get; set; } }
public class Experience { public int Id { get; set; } public string Company { get; set; } = ""; public string Role { get; set; } = ""; public string? Description { get; set; } public DateTime StartDate { get; set; } public DateTime? EndDate { get; set; } public string? Location { get; set; } public string? CompanyUrl { get; set; } public string? LogoUrl { get; set; } public int SortOrder { get; set; } public DateTime CreatedAt { get; set; } public DateTime UpdatedAt { get; set; } }
public class Testimonial { public int Id { get; set; } public string ClientName { get; set; } = ""; public string? ClientTitle { get; set; } public string? ClientAvatar { get; set; } public string Content { get; set; } = ""; public int Rating { get; set; } public int? ProjectId { get; set; } public bool IsPublished { get; set; } public int SortOrder { get; set; } public DateTime CreatedAt { get; set; } public DateTime UpdatedAt { get; set; } }
public class ContactMessage { public int Id { get; set; } public string Name { get; set; } = ""; public string Email { get; set; } = ""; public string? Subject { get; set; } public string Message { get; set; } = ""; public bool IsRead { get; set; } public DateTime? RepliedAt { get; set; } public DateTime CreatedAt { get; set; } }
public class SiteSetting { public int Id { get; set; } public string Key { get; set; } = ""; public string? Value { get; set; } public DateTime UpdatedAt { get; set; } }
public class ErrorLog { public int Id { get; set; } public DateTime Timestamp { get; set; } public string Level { get; set; } = "Error"; public string? Source { get; set; } public string Message { get; set; } = ""; public string? StackTrace { get; set; } public string? RequestPath { get; set; } public string? Method { get; set; } public int? StatusCode { get; set; } public int? UserId { get; set; } public string? UserAgent { get; set; } public string? IpAddress { get; set; } public bool IsResolved { get; set; } public DateTime? ResolvedAt { get; set; } public string? ResolvedBy { get; set; } public DateTime CreatedAt { get; set; } }

public class Contract { public int Id { get; set; } public string Title { get; set; } = ""; public string? ClientName { get; set; } public string? ClientEmail { get; set; } public decimal? Amount { get; set; } public string? Currency { get; set; } public DateTime? StartDate { get; set; } public DateTime? EndDate { get; set; } public string Status { get; set; } = "Pending"; public string? Description { get; set; } public string? Notes { get; set; } public DateTime CreatedAt { get; set; } public DateTime UpdatedAt { get; set; } }

public class ProjectPhase { public int Id { get; set; } public int ProjectId { get; set; } public string Title { get; set; } = ""; public string? Description { get; set; } public string Status { get; set; } = "Pending"; public int Progress { get; set; } public int SortOrder { get; set; } public DateTime? StartDate { get; set; } public DateTime? EndDate { get; set; } public int? ContractId { get; set; } public string? ClientName { get; set; } public DateTime? CompletedAt { get; set; } public DateTime CreatedAt { get; set; } public DateTime UpdatedAt { get; set; } }
